name: aes_crypt
description: (Null safety) Dart encryption library for encrypting/decrypting files, plain text and binary data in AES Crypt file format.
version: 2.0.0
homepage: https://github.com/fsmdeveloper/aes_crypt2
repository: https://github.com/fsmdeveloper/aes_crypt2

environment:
  sdk: ">=2.7.0 <3.0.0"

# dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
